basePath: /api/v1
definitions:
  controller.User:
    properties:
      age:
        example: 25
        type: integer
      id:
        example: 1
        type: integer
      name:
        example: 张三
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: HarborArk 项目 API 文档
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: HarborArk API
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: 获取所有用户的列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controller.User'
            type: array
      summary: 获取用户列表
      tags:
      - 用户管理
    post:
      consumes:
      - application/json
      description: 创建新用户
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/controller.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controller.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: 创建用户
      tags:
      - 用户管理
  /users/{id}:
    get:
      consumes:
      - application/json
      description: 根据用户ID获取单个用户信息
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      summary: 根据ID获取用户
      tags:
      - 用户管理
swagger: "2.0"
